apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: quay.io/sameersbn/nginx:1.8.0-6
      ports:
        - containerPort: 80
          protocol: TCP
